### ISSUE TITLE
Должен замещаться "самый старый"

### ISSUE THREAD

**Issue by coursar** [Nikrom13/Circular-buffer#2]
https://github.com/Nikrom13/Circular-buffer/blob/d6915d6a0ce50bb8f617e581dbdced3a8f8d9654/src/main/java/ru/itpark/buffer/repository/CityRepository.java#L18

**Comment by Nikrom13** [comment]
так получилось из-за сортировки, если убрать сортировку, тогда там ставим место 4, 0 и замещается самый старый, но в этом случае не получается список расположить сверху вниз, чтобы пропадал нижний и появлялся верхний

**Comment by coursar** [comment]
4 нужно как минимум, вынести в поле, а не хардкодить
