### ISSUE TITLE
Зачем нужна сортировка?

### ISSUE THREAD

**Issue by coursar** [Nikrom13/Circular-buffer#3]
https://github.com/Nikrom13/Circular-buffer/blob/d6915d6a0ce50bb8f617e581dbdced3a8f8d9654/src/main/java/ru/itpark/buffer/repository/CityRepository.java#L22-L34

**Comment by Nikrom13** [comment]
Сортировку сделал чтобы список отображался сверху вниз, как новости, когда нижняя уезжает, а сверху появляется новая, возможно ли это реализовать другим образом?

**Comment by coursar** [comment]
для этого нужно использовать позицию, а не id
